

CREATE TABLE CLIENTE(
    CLIENTE_ID NUMERIC(6) NOT NULL PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(260) NOT NULL
);

CREATE SEQUENCE SEQ_CLIENTE;

INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL)VALUES(SEQ_CLIENTE.NEXTVAL, 'CLIENTE 1');


INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL)VALUES(SEQ_CLIENTE.NEXTVAL, 'CLIENTE 2');
INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL)VALUES(SEQ_CLIENTE.NEXTVAL, 'CLIENTE 3');
INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL)VALUES(SEQ_CLIENTE.NEXTVAL, 'CLIENTE 4');
INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL)VALUES(SEQ_CLIENTE.NEXTVAL, 'CLIENTE 5');
INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL)VALUES(SEQ_CLIENTE.NEXTVAL, 'CLIENTE 6');
INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL)VALUES(SEQ_CLIENTE.NEXTVAL, 'CLIENTE 7');
INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL)VALUES(SEQ_CLIENTE.NEXTVAL, 'CLIENTE 8');

COMMIT;


